### ISSUE TITLE
API search on title and body is case sensitive

### ISSUE THREAD

**Issue by ivanstegic** [WhiteHouse/ndoch-hackathon#12]
It seems that the "title" and "body" fields in the API are case sensitive -- they probably shouldn't be :) 

Trying to find petitions about Westboro Baptist Church, hit the API with:

> https://api.whitehouse.gov/v1/petitions.jsonp?title=westboro

Get no results. Try it with an uppercase "W" and you get results:

> https://api.whitehouse.gov/v1/petitions.jsonp?title=Westboro

This shouldn't be the case -- we should get results for both cases.

**Comment by stevegrunwell** [comment]
Already opened a ticket a few days ago on the Petitions project :): https://github.com/WhiteHouse/petitions/issues/60

**Comment by ivanstegic** [comment]
@stevegrunwell thanks Steve, but I was asked to include it here so that they could review them all in one spot

**Comment by welschp** [comment]
Definitely on our radar, thanks for flagging.

**Comment by theneonlobster** [comment]
This issue was resolved in the last release.

**Comment by BigSauce** [comment]
Confirmed!  Thanks!

**Comment by BigSauce** [comment]
@theneonlobster: when you say "in the last release", are you referring to the initial release of the We the People API?  If you were referring to a later release, then I did not know another version had been released.  How can developers remain privy to new releases?
