### ISSUE TITLE
Invitation to pre-hackathon dinner at MapBox HQ

### ISSUE THREAD

**Issue by heyitsgarrett** [WhiteHouse/ndoch-hackathon#8]
I'd like to extend an invitation to participants of the hackathon to join us the night before for dinner and drinks. It'll be a great opportunity to meet folks before diving in to the API the next morning.

_Note: this is an unofficial event and is not sponsored or endorsed by The White House._

---

**Pre-Hackathon Meet-n-Greet at MapBox HQ**
:clock7: Friday, May 31st, 7PM
:house: [1714 14th St NW, Rear Entrance](https://maps.google.com/maps?q=mapbox&hq=mapbox&hnear=Washington,+District+of+Columbia+20009&t=m&z=15&iwloc=A)

![640x300](https://f.cloud.github.com/assets/200357/513249/20f71dde-be3a-11e2-9a1f-3c98b638628f.png)

Please RSVP by commenting here or emailing me at [garrett@mapbox.com](mailto:garrett@mapbox.com?subject= RSVP: Pre-hackathon dinner). Looking forward to meeting everyone!

---

Tying in to #1

**Comment by jmandzik** [comment]
Mighty kind of you.  I'm in.

**Comment by ivanstegic** [comment]
I'll be in town with my fam the night before -- I'll most likely be in, but let me confirm closer to the time!

**Comment by carldanley** [comment]
I arrive at 8:28pm. If the event is still going on, I'd love to meetup.

**Comment by eshtadc** [comment]
I'm local and looking forward to coming.  Thanks for hosting.

**Comment by yoni** [comment]
I'm in, provided I make it into town that evening. See you soon, @heyitsgarrett!  :)

**Comment by bryanbraun** [comment]
Thanks for the invite... count me in as well.

**Comment by dlapiduz** [comment]
Count me in, will be there. Thanks!

**Comment by nickcatal** [comment]
Cool, I'll be there as well

**Comment by cndreisbach** [comment]
Fantastic! Thanks for doing this, and I'll be there.

**Comment by colmdoyle** [comment]
Bah, don't get into town until 10pm. Would have enjoyed meeting up before the hack!

**Comment by fuhteems** [comment]
Sounds great, I'd love to join!

**Comment by ivanstegic** [comment]
I'll be there!

**Comment by heyitsgarrett** [comment]
Hi folks, thanks for RSVPing! For those that can make it - are there any dietary restrictions? If so, [let me know](mailto:garrett@mapbox.com) and we can plan accordingly. Looking forward to next week's events.

**Comment by typesend** [comment]
+1 See you there!

**Comment by danielsmc** [comment]
I'll be there. Thanks for the invitation!

**Comment by sinak** [comment]
I'm in too! Thanks for the invite!

**Comment by jessebeach** [comment]
+1, I'll be there.

**Comment by heyitsgarrett** [comment]
Hi folks, looking forward to seeing everyone tonight. Just a quick reminder about our location - we're actually in an alleyway between R St NW and S St NW. We've got a light blue building and big glass doors, so it should be easy to spot us.

See you tonight!

![](https://f.cloud.github.com/assets/200357/513249/20f71dde-be3a-11e2-9a1f-3c98b638628f.png)

**Comment by waldoj** [comment]
...and I totally forgot to either RSVP or attend. I'm an idiot. :-1:

**Comment by typesend** [comment]
@waldoj Just don't forget to show up tomorrow. Otherwise we'll really start to wonder Where's Waldo. 
![image](https://f.cloud.github.com/assets/8130/594248/a4fb68ae-ca67-11e2-9ab6-df5902aa5e47.png)

**Comment by jmandzik** [comment]
Oh snap. Best github issue update ever

**Comment by waldoj** [comment]
No, it's not. Trust me.

**Comment by heyitsgarrett** [comment]
Thanks for coming, everyone, and for a great weekend last week!
