### ISSUE TITLE
We the Entities

### ISSUE THREAD

**Issue by yoni** [WhiteHouse/ndoch-hackathon#9]
I've created a new API for extracting entities, locations, sentiment and more from petition data. I hope that other folks can use this API to augment their apps with rich data from the petition text.

This is currently in rough form, so I'm eager to get people's feedback, ideas, pull requests and usage examples. I'll continue working on it this weekend, so please expect the API to change A LOT.
#### The live app and an example call to the API:

http://www.wetheentities.org/
http://www.wetheentities.org/petitions/51942b9b2f2c888e2f00000c.json
#### The codebase and issues:

https://github.com/yoni/wetheentities
https://github.com/yoni/wetheentities/issues

Best,
@yoni

**Comment by bryanbraun** [comment]
Yoni, this is really great.

**Comment by yoni** [comment]
Thanks @bryanbraun!

I've added a couple of [examples](http://wetheentities.herokuapp.com/examples/index) to the app. Please don't hesitate to reach out if you have any questions.

**Comment by eshtadc** [comment]
Thanks @yoni.  I was just realizing how much something like this was necessary to be able to progress with the work I want to do and you magically posted at the right moment!  Fantastic.

**Comment by yoni** [comment]
@lkhaas i'd love to see what you're working on! again, feel free to ping me with feature requests or any issues. i'd love to help make this usable.

**Comment by yoni** [comment]
Please send me links to your apps so that I can add them to the examples page for We the Entities. :)

**Comment by ivanstegic** [comment]
WTP Instant Search Repo: https://github.com/ivanstegic/wethepeople-instantsearch

WTP Instant Seatch Github page: http://ivanstegic.github.io/wethepeople-instantsearch

**Comment by stevegrunwell** [comment]
Project: https://github.com/buckii/we-the-people-wordpress
Presentation: http://stevegrunwell.github.io/we-the-people-wordpress-talk/

**Comment by ivanstegic** [comment]
@lkhaas Yes, you can actually get the JSONP request using .js instead, like this:

> http://wetheentities.herokuapp.com/petitions/51942b9b2f2c888e2f00000c.js

**Comment by ivanstegic** [comment]
@lkhaas Actually, this is the right one:

> http://wetheentities.herokuapp.com/petitions/50a3fd762f2c88cd65000015.js?callback=jQuery191046733513893559575_1370274143150&_=1370274143157

**Comment by yoni** [comment]
Thanks @ivanstegic. I'll be sure to update the documentation with that!

**Comment by yoni** [comment]
@stevegrunwell do you happen to have a screenshot with entity or sentiment stuff in it? otherwise, i'll use the one you posted on the WH gallery issue.

**Comment by yoni** [comment]
@stevegrunwell @ivanstegic OK this should be in the docs now. Thanks for the feedback people, and keep it coming. :)

**Comment by stevegrunwell** [comment]
@yoni Shoot, I think my last comment ended up on the wrong thread. My plugin isn't using We The Entities (at least not at this point), please feel free to disregard. Great work though, WTE is an awesome extension to WTP!

**Comment by yoni** [comment]
@stevegrunwell understood. i removed it.

i'd still love to get WTE integrated into your plugin, though! :)

**Comment by yoni** [comment]
I've updated the domain name for the app to: http://www.wetheentities.org/

The previous domain name should still work, but I suggest that you point your apps to the new one at your earliest convenience.
